// Hand-authored UI/UX case studies — designed in Figma, exported as a tall
// case-study image, sliced into stackable segments under /public/work/<slug>/.
// Defined here (not WordPress) so they ship with the code and survive CMS resets.
// Spread into DEMO_ALL in queries.js → getProjectBySlug resolves them first,
// so they render at /work/<slug> and appear as cards in the Work archive.
export const CASE_STUDIES = [
  {
    _id: "cs-obscura",
    slug: "obscura",
    title: "OBSCURA — Maison de Parfum",
    category: "UI/UX",
    year: "2026",
    featured: true,
    order: 1,
    accentColor: "#C49A5C",
    brief:
      "A dark, slow luxury perfume house — *composed like an editorial,* ink and shadow and a single brass.",
    role: "UI/UX & Art Direction",
    roleTags: ["Art Direction", "UI/UX", "Luxury E-commerce", "Editorial"],
    platform: "Web",
    timeline: "Concept",
    niche: "Luxury Perfume E-commerce",
    description:
      "OBSCURA is a small house of seven extraits — and its storefront had to feel like the bottle: heavy, dark, deliberate. Instead of the bright beauty-marketplace grid or the faux-luxe gold-gradient template, OBSCURA is composed like an editorial: ink and shadow, a single brass accent, a high-contrast serif (Cormorant Garamond) against vast negative space, and macro fragrance photography that does the selling. Designed end to end — a hero that sells the feeling, a seven-piece collection, an olfactory pyramid (top/heart/base notes), an editorial campaign band, and the maison story. Hand-coded, AA-clean.",
    challenge: "",
    context: "",
    outcome: "",
    process: [],
    thumbnailUrl: "/work/obscura/cover.jpg",
    detailImageUrls: [
      "/work/obscura/01.webp",
      "/work/obscura/02.webp",
      "/work/obscura/03.webp",
      "/work/obscura/04.webp",
      "/work/obscura/05.webp",
    ],
  },
  {
    _id: "cs-b-side",
    slug: "b-side",
    title: "B-SIDE — Independent Record Label",
    category: "UI/UX",
    year: "2026",
    featured: true,
    order: 1,
    accentColor: "#FF5A36",
    brief:
      "An independent vinyl label, *pressed in pixels* — print-shop maximalism, not another clean shop.",
    role: "UI/UX & Art Direction",
    roleTags: ["Art Direction", "UI/UX", "E-commerce", "Design System"],
    platform: "Web",
    timeline: "Concept",
    niche: "Independent Record Label",
    description:
      "B-Side is a small-batch vinyl record label out of Bristol — and its storefront had to do two jobs at once: sell records, and be the brand. So instead of the usual clinical marketplace grid or the beige 'curated' template, B-Side goes full print-shop maximalism: risograph inks, halftone, a literal wall of records, oversized condensed type bleeding off the page, and a persistent record-player bar that follows you as you scroll. Designed and built end to end — a hero that sells the ritual, a catalogue wall, an artist spotlight, a live-sessions band and a manifesto. Anton + Archivo + Space Mono on ink; electric blue, red-orange and acid yellow. Hand-coded, with real duotone photography.",
    challenge: "",
    context: "",
    outcome: "",
    process: [],
    thumbnailUrl: "/work/b-side/cover.jpg",
    detailImageUrls: [
      "/work/b-side/01.webp",
      "/work/b-side/02.webp",
      "/work/b-side/03.webp",
      "/work/b-side/04.webp",
      "/work/b-side/05.webp",
    ],
  },
  {
    _id: "cs-roast-house",
    slug: "roast-house",
    title: "Roast House — Specialty Coffee",
    category: "UI/UX",
    year: "2026",
    featured: true,
    order: 2,
    accentColor: "#C8643C",
    brief:
      "Specialty coffee, *editorial and photo-led* — dark as a good espresso, built for people who care where their beans come from.",
    role: "UI/UX & Product Design",
    roleTags: ["Product Design", "UI/UX", "E-commerce", "Design System"],
    platform: "Web",
    timeline: "Concept",
    niche: "Specialty Coffee E-commerce",
    description:
      "Roast House is a storefront for a small-batch specialty coffee roaster — built for people who care where their beans come from and how fresh they are. Specialty coffee online is usually either a clinical marketplace grid or the same beige, hand-lettered template every café uses. Roast House goes the other way: editorial and photo-led, dark as a good espresso. Designed end to end — a home that sells the ritual, a bestselling-roasts grid with honest tasting notes, and a product page with origin, process, a grind picker and a freshness promise. Fraunces + Inter, terracotta and amber on deep espresso.",
    challenge: "",
    context: "",
    outcome: "",
    process: [],
    thumbnailUrl: "/work/roast-house/cover.jpg",
    detailImageUrls: [
      "/work/roast-house/01.webp",
      "/work/roast-house/02.webp",
      "/work/roast-house/03.webp",
      "/work/roast-house/04.webp",
      "/work/roast-house/05.webp",
      "/work/roast-house/06.webp",
    ],
  },
  {
    _id: "cs-meterly",
    slug: "meterly",
    title: "Meterly — Product Analytics",
    category: "UI/UX",
    year: "2026",
    featured: true,
    order: 2,
    accentColor: "#1B3CD6",
    brief:
      "Product analytics, *reimagined* — calm, legible, and built to feel human, not another dark dashboard.",
    role: "UI/UX & Product Design",
    roleTags: ["Product Design", "UI/UX", "Data Visualization", "Design System"],
    platform: "Web App",
    timeline: "Concept",
    niche: "Product Analytics SaaS",
    description:
      "A product-analytics workspace that turns raw events into the metrics teams actually trust — calm, legible, and built to feel human. Four surfaces in one editorial system: an overview that surfaces what changed, a sortable cohort table, a single-metric report with discussion built in, and an integrations hub. Cool porcelain palette, mono numerals, hand-built charts (no stock kits), and a three-voice type system — Instrument Serif, IBM Plex Mono and Inter.",
    challenge: "",
    context: "",
    outcome: "",
    process: [],
    thumbnailUrl: "/work/meterly/cover.jpg",
    detailImageUrls: [
      "/work/meterly/01.webp",
      "/work/meterly/02.webp",
      "/work/meterly/03.webp",
      "/work/meterly/04.webp",
      "/work/meterly/05.webp",
      "/work/meterly/06.webp",
    ],
  },
];
