// AUTO-GENERATED from envato-themes/_portfolio/manifest.json — 16 live-demo projects (Development).
// Each renders as a /work card + a detail page that embeds the live demo iframe.
export const DEMO_PROJECTS = [
  {
    "_id": "demo-lumen-analytics",
    "slug": "lumen-analytics",
    "title": "Lumen — Product Analytics SaaS",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 100,
    "accentColor": "#3b2fd6",
    "brief": "The analytics layer your whole team understands",
    "role": "UI/UX Design · Web Design · SaaS · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "SaaS",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Product Analytics SaaS",
    "description": "A product-analytics platform that turns scattered data into clear answers — funnels, retention, and AI insights designed for the whole team, not just analysts.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/lumen-analytics/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/lumen-analytics/index.html"
  },
  {
    "_id": "demo-halo-ai",
    "slug": "halo-ai",
    "title": "Halo — AI Support Assistant",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 101,
    "accentColor": "#7c5cff",
    "brief": "The AI teammate that answers in seconds",
    "role": "UI/UX Design · Web Design · AI · Product Design",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "AI",
      "Product Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "AI Support Assistant",
    "description": "A conversational-AI support product that resolves customer chats instantly in 50+ languages, trained on your help docs in minutes.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/halo-ai/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/halo-ai/index.html"
  },
  {
    "_id": "demo-float-fintech",
    "slug": "float-fintech",
    "title": "Float — Consumer Fintech",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 102,
    "accentColor": "#10b981",
    "brief": "Money that moves as fast as you do",
    "role": "UI/UX Design · Mobile · Fintech · Branding",
    "roleTags": [
      "UI/UX Design",
      "Mobile",
      "Fintech",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Consumer Fintech",
    "description": "A consumer banking app — 4.30% APY, automatic round-up investing, and zero fees — designed around a clean mobile experience.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/float-fintech/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/float-fintech/index.html"
  },
  {
    "_id": "demo-ascend-crypto",
    "slug": "ascend-crypto",
    "title": "Ascend — Crypto Exchange",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 103,
    "accentColor": "#1fd17b",
    "brief": "Buy, sell & stake crypto with confidence",
    "role": "UI/UX Design · Web Design · Crypto · Product Design",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Crypto",
      "Product Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Crypto Exchange",
    "description": "A secure crypto exchange and wallet — trade 200+ assets, earn staking rewards, and store everything in insured cold storage.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/ascend-crypto/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/ascend-crypto/index.html"
  },
  {
    "_id": "demo-forge-academy",
    "slug": "forge-academy",
    "title": "Forge Academy — Coding Bootcamp",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 104,
    "accentColor": "#c4f135",
    "brief": "Become a developer in 16 weeks",
    "role": "UI/UX Design · Web Design · EdTech · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "EdTech",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Coding Bootcamp",
    "description": "A live coding-bootcamp brand built around outcomes — a 16-week roadmap, 1:1 mentorship, and a job guarantee.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/forge-academy/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/forge-academy/index.html"
  },
  {
    "_id": "demo-sprout-kids",
    "slug": "sprout-kids",
    "title": "Sprout — Kids Learning",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 105,
    "accentColor": "#3fc06b",
    "brief": "Learning that feels like play",
    "role": "UI/UX Design · Web Design · EdTech · Illustration",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "EdTech",
      "Illustration"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Kids Learning",
    "description": "A joyful, kid-safe learning platform that turns reading, math, and science into games — with a parent dashboard.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/sprout-kids/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/sprout-kids/index.html"
  },
  {
    "_id": "demo-cedar-architecture",
    "slug": "cedar-architecture",
    "title": "Cedar & Stone — Architecture Studio",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 106,
    "accentColor": "#15140f",
    "brief": "Spaces that hold a life",
    "role": "Art Direction · Web Design · Branding · Editorial Design",
    "roleTags": [
      "Art Direction",
      "Web Design",
      "Branding",
      "Editorial Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Architecture Studio",
    "description": "Brand and website for an award-winning architecture studio — a portfolio-first, editorial experience that lets the work speak.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/cedar-architecture/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/cedar-architecture/index.html"
  },
  {
    "_id": "demo-bedrock-construction",
    "slug": "bedrock-construction",
    "title": "Bedrock — Design-Build Construction",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 107,
    "accentColor": "#f25c05",
    "brief": "We build it right, the first time",
    "role": "Brand Identity · Web Design · Construction",
    "roleTags": [
      "Brand Identity",
      "Web Design",
      "Construction"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Design-Build Construction",
    "description": "A bold, industrial brand for a design-build contractor — fixed-price confidence and a no-surprises process, start to finish.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/bedrock-construction/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/bedrock-construction/index.html"
  },
  {
    "_id": "demo-pulse-gym",
    "slug": "pulse-gym",
    "title": "Pulse — Gym & Fitness",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 108,
    "accentColor": "#e8242b",
    "brief": "Train like you mean it",
    "role": "UI/UX Design · Web Design · Branding · Fitness",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Branding",
      "Fitness"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Gym & Fitness",
    "description": "A high-energy gym brand — coached classes, memberships, and community — built to fill classes and convert members.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/pulse-gym/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/pulse-gym/index.html"
  },
  {
    "_id": "demo-stillwater-yoga",
    "slug": "stillwater-yoga",
    "title": "Stillwater — Yoga Studio",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 109,
    "accentColor": "#7c9885",
    "brief": "Find your center, one breath at a time",
    "role": "Art Direction · Web Design · Wellness · Branding",
    "roleTags": [
      "Art Direction",
      "Web Design",
      "Wellness",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Yoga Studio",
    "description": "A calm, editorial brand for a yoga and meditation studio — all-levels classes, in studio and on demand.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/stillwater-yoga/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/stillwater-yoga/index.html"
  },
  {
    "_id": "demo-harvest-dining",
    "slug": "harvest-dining",
    "title": "Harvest Table — Restaurant",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 110,
    "accentColor": "#b4530a",
    "brief": "Seasonal cooking, honest and warm",
    "role": "Web Design · Branding · Restaurant · Art Direction",
    "roleTags": [
      "Web Design",
      "Branding",
      "Restaurant",
      "Art Direction"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Restaurant",
    "description": "A farm-to-fire restaurant brand — a seasonal menu, warm photography, and a reservation-first experience.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/harvest-dining/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/harvest-dining/index.html"
  },
  {
    "_id": "demo-marisol-hotel",
    "slug": "marisol-hotel",
    "title": "The Marisol — Resort & Hospitality",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 111,
    "accentColor": "#1d7e86",
    "brief": "Where the day slows down",
    "role": "UI/UX Design · Web Design · Hospitality · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Hospitality",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Resort & Hospitality",
    "description": "A luxury beachfront resort site — sea-view suites, an ocean spa, and dining — with an elegant booking experience.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/marisol-hotel/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/marisol-hotel/index.html"
  },
  {
    "_id": "demo-summit-adventure",
    "slug": "summit-adventure",
    "title": "Summit Co. — Adventure Travel",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 112,
    "accentColor": "#e0682f",
    "brief": "Go further than the trailhead",
    "role": "Web Design · Branding · Travel",
    "roleTags": [
      "Web Design",
      "Branding",
      "Travel"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Adventure Travel",
    "description": "A rugged guided-expedition brand — treks and climbs with difficulty ratings and an outdoors-first identity.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/summit-adventure/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/summit-adventure/index.html"
  },
  {
    "_id": "demo-hale-law",
    "slug": "hale-law",
    "title": "Hale Law — Personal Injury Law",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 113,
    "accentColor": "#d6282f",
    "brief": "Hurt? You deserve a fighter",
    "role": "Web Design · Branding · Legal · CRO",
    "roleTags": [
      "Web Design",
      "Branding",
      "Legal",
      "CRO"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Personal Injury Law",
    "description": "A bold personal-injury attorney brand built to convert — a contingency model, big results, and 24/7 contact.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/hale-law/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/hale-law/index.html"
  },
  {
    "_id": "demo-bloom-florist",
    "slug": "bloom-florist",
    "title": "Bloom — Florist · E-commerce",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 114,
    "accentColor": "#c64f7f",
    "brief": "Flowers that make the whole room smile",
    "role": "UI/UX Design · E-commerce · Branding · Web Design",
    "roleTags": [
      "UI/UX Design",
      "E-commerce",
      "Branding",
      "Web Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Florist · E-commerce",
    "description": "A same-day florist e-commerce experience — hand-tied bouquets, occasion shopping, and flower subscriptions.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/bloom-florist/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/bloom-florist/index.html"
  },
  {
    "_id": "demo-faraway-travel",
    "slug": "faraway-travel",
    "title": "Faraway — Editorial · Travel Journal",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 115,
    "accentColor": "#1b6f74",
    "brief": "Slow travel, told well",
    "role": "Art Direction · Editorial Design · Web Design",
    "roleTags": [
      "Art Direction",
      "Editorial Design",
      "Web Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Editorial · Travel Journal",
    "description": "A photo-led travel journal — long-form dispatches and guides with a refined, magazine-grade editorial system.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/faraway-travel/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/faraway-travel/index.html"
  }
];
