// AUTO-GENERATED from envato-themes/_portfolio/manifest.json — 16 live-demo projects (Development).
// Each renders as a /work card + a detail page that embeds the live demo iframe.
export const DEMO_PROJECTS = [
  {
    "_id": "demo-lumen-analytics",
    "slug": "lumen-analytics",
    "title": "Lumen — Product Analytics SaaS",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 100,
    "accentColor": "#3b2fd6",
    "brief": "The analytics layer your whole team understands",
    "role": "UI/UX Design · Web Design · SaaS · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "SaaS",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Product Analytics SaaS",
    "description": "A product-analytics platform that turns scattered product data into clear answers — funnels, retention, and AI insights designed for the whole team, not just analysts.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/lumen-analytics/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/lumen-analytics/index.html"
  },
  {
    "_id": "demo-vault-banking",
    "slug": "vault-banking",
    "title": "Vault — Business Banking · Fintech",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 101,
    "accentColor": "#16324f",
    "brief": "Your money, working as hard as you do",
    "role": "UI/UX Design · Web Design · Fintech · Product Design",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Fintech",
      "Product Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Business Banking · Fintech",
    "description": "A modern business banking platform: high-yield accounts, corporate cards, automated bill pay, and treasury — with bank-grade security and a compliance-ready experience.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/vault-banking/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/vault-banking/index.html"
  },
  {
    "_id": "demo-ascend-crypto",
    "slug": "ascend-crypto",
    "title": "Ascend — Crypto Exchange",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 102,
    "accentColor": "#312e81",
    "brief": "Buy, sell, and hold crypto with confidence",
    "role": "UI/UX Design · Web Design · Fintech · Crypto",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Fintech",
      "Crypto"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Crypto Exchange",
    "description": "A secure crypto exchange and wallet — trade 200+ assets, earn staking rewards, and store everything in insured cold storage, in one clean app.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/ascend-crypto/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/ascend-crypto/index.html"
  },
  {
    "_id": "demo-meridian-wealth",
    "slug": "meridian-wealth",
    "title": "Meridian — Wealth Management",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 103,
    "accentColor": "#14532d",
    "brief": "Grow your wealth with a plan you understand",
    "role": "UI/UX Design · Web Design · Fintech · Product Design",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Fintech",
      "Product Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Wealth Management",
    "description": "An automated wealth-management product — diversified portfolios, auto-rebalancing, and tax-loss harvesting, explained clearly for everyday investors.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/meridian-wealth/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/meridian-wealth/index.html"
  },
  {
    "_id": "demo-forge-academy",
    "slug": "forge-academy",
    "title": "Forge Academy — EdTech · Coding Bootcamp",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 104,
    "accentColor": "#0d9488",
    "brief": "Become a developer in 16 weeks",
    "role": "UI/UX Design · Web Design · EdTech · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "EdTech",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "EdTech · Coding Bootcamp",
    "description": "A coding-bootcamp platform with live cohorts, real projects, 1:1 mentorship, and job-placement tracking.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/forge-academy/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/forge-academy/index.html"
  },
  {
    "_id": "demo-sprout-kids",
    "slug": "sprout-kids",
    "title": "Sprout — Kids EdTech",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 105,
    "accentColor": "#65a30d",
    "brief": "Learning that feels like play",
    "role": "UI/UX Design · Web Design · EdTech · Illustration",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "EdTech",
      "Illustration"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Kids EdTech",
    "description": "A joyful, ad-free learning platform for kids 4–12 — reading, math, and science turned into games parents can trust.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/sprout-kids/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/sprout-kids/index.html"
  },
  {
    "_id": "demo-cedar-architecture",
    "slug": "cedar-architecture",
    "title": "Cedar & Stone — Architecture Studio",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 106,
    "accentColor": "#1c1917",
    "brief": "Spaces that hold a life",
    "role": "Art Direction · Web Design · Branding · Editorial Design",
    "roleTags": [
      "Art Direction",
      "Web Design",
      "Branding",
      "Editorial Design"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Architecture Studio",
    "description": "Brand and website for an award-winning architecture studio — a portfolio-first, editorial experience that lets the work speak.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/cedar-architecture/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/cedar-architecture/index.html"
  },
  {
    "_id": "demo-atelier-interior",
    "slug": "atelier-interior",
    "title": "Atelier Noma — Interior Design",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 107,
    "accentColor": "#3f3f46",
    "brief": "Interiors with quiet confidence",
    "role": "Art Direction · Web Design · Branding",
    "roleTags": [
      "Art Direction",
      "Web Design",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Interior Design",
    "description": "A portfolio site for a residential and hospitality interior-design studio — warm, tactile, and considered.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/atelier-interior/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/atelier-interior/index.html"
  },
  {
    "_id": "demo-pulse-gym",
    "slug": "pulse-gym",
    "title": "Pulse — Fitness · Gym",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 108,
    "accentColor": "#dc2626",
    "brief": "Train like you mean it",
    "role": "UI/UX Design · Web Design · Branding · Fitness",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Branding",
      "Fitness"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Fitness · Gym",
    "description": "A bold strength-and-conditioning gym brand with class booking, membership tiers, and an energetic, high-contrast identity.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/pulse-gym/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/pulse-gym/index.html"
  },
  {
    "_id": "demo-stillwater-yoga",
    "slug": "stillwater-yoga",
    "title": "Stillwater — Wellness · Yoga",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 109,
    "accentColor": "#0f766e",
    "brief": "Find your center, one breath at a time",
    "role": "UI/UX Design · Web Design · Wellness · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Wellness",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Wellness · Yoga",
    "description": "A calm yoga-studio experience with class schedules, on-demand sessions, and a serene, restorative aesthetic.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/stillwater-yoga/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/stillwater-yoga/index.html"
  },
  {
    "_id": "demo-harvest-dining",
    "slug": "harvest-dining",
    "title": "Harvest Table — Restaurant",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 110,
    "accentColor": "#b45309",
    "brief": "Seasonal cooking, honest and warm",
    "role": "Art Direction · Web Design · Branding · Hospitality",
    "roleTags": [
      "Art Direction",
      "Web Design",
      "Branding",
      "Hospitality"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Restaurant",
    "description": "A farm-to-fire restaurant brand — seasonal menu, reservations, and an inviting story-led site.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/harvest-dining/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/harvest-dining/index.html"
  },
  {
    "_id": "demo-atlas-tours",
    "slug": "atlas-tours",
    "title": "Atlas — Travel · Tours",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 111,
    "accentColor": "#0e7490",
    "brief": "See the world, the right way",
    "role": "UI/UX Design · Web Design · Travel · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Travel",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Travel · Tours",
    "description": "A small-group adventure-travel brand — destination discovery, trip cards with pricing, and responsible-travel credentials.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/atlas-tours/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/atlas-tours/index.html"
  },
  {
    "_id": "demo-marisol-hotel",
    "slug": "marisol-hotel",
    "title": "The Marisol — Hospitality · Hotel",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 112,
    "accentColor": "#0891b2",
    "brief": "Where the day slows down",
    "role": "UI/UX Design · Web Design · Hospitality · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Hospitality",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Hospitality · Hotel",
    "description": "A beachfront resort site — sea-view suites, spa, dining, and a frictionless direct-booking flow.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/marisol-hotel/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/marisol-hotel/index.html"
  },
  {
    "_id": "demo-verity-law",
    "slug": "verity-law",
    "title": "Verity Legal — Law Firm",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 113,
    "accentColor": "#7f1d1d",
    "brief": "When it matters most",
    "role": "UI/UX Design · Web Design · Branding · Legal",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "Branding",
      "Legal"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Law Firm",
    "description": "A full-service law-firm brand that leads with results and institutional gravitas — built to win high-stakes clients.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/verity-law/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/verity-law/index.html"
  },
  {
    "_id": "demo-bloom-florist",
    "slug": "bloom-florist",
    "title": "Bloom — Florist · E-commerce",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 114,
    "accentColor": "#be185d",
    "brief": "Flowers that make the whole room smile",
    "role": "UI/UX Design · Web Design · E-commerce · Branding",
    "roleTags": [
      "UI/UX Design",
      "Web Design",
      "E-commerce",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Florist · E-commerce",
    "description": "A same-day florist e-commerce experience with hand-tied arrangements, gifting, and flower subscriptions.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/bloom-florist/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/bloom-florist/index.html"
  },
  {
    "_id": "demo-fieldnotes-magazine",
    "slug": "fieldnotes-magazine",
    "title": "Field Notes — Editorial · Magazine",
    "category": "Development",
    "year": "2026",
    "featured": false,
    "order": 115,
    "accentColor": "#161513",
    "brief": "Stories for the curious",
    "role": "Editorial Design · Web Design · UI/UX Design · Branding",
    "roleTags": [
      "Editorial Design",
      "Web Design",
      "UI/UX Design",
      "Branding"
    ],
    "platform": "WordPress + Elementor (custom theme)",
    "niche": "Editorial · Magazine",
    "description": "A reader-funded online magazine — longform features, essays, a podcast, and membership, in a clean editorial system.",
    "challenge": "",
    "context": "",
    "outcome": "",
    "process": [],
    "thumbnailUrl": "/demos/fieldnotes-magazine/card.jpg",
    "detailImageUrls": [],
    "demoUrl": "/demos/fieldnotes-magazine/index.html"
  }
];
